apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
  namespace: nussknacker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: touk/grafana:4.4.1-esp
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_SERVER_ROOT_URL
          value: "%(protocol)s://%(domain)s:/grafana"
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: nussknacker
spec:
  ports:
  - name: http
    port: 3000
  selector:
    app: grafana
