apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: nussknacker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: touk/nginx:nussknacker
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "0.25Gi"
            cpu: "0.125"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nussknacker
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: nginx
